apiVersion: v1
kind: Service
metadata:
  name: config-server-with-kafka
  labels:
    app: config-server-with-kafka
spec:
  selector:
    app: config-server-with-kafka
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10000
      nodePort: 30777